// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptkmfeinqmisluyljlyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0a21mZWlucW1pc2x1eWxqbHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NzQxMjQsImV4cCI6MjA3MTA1MDEyNH0.fJsnX8h-erc4fImqEEaw14REpWm4vcP8KP_yHvs5EWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});